### ISSUE TITLE
进入子层级时重复打印父层级描述

### ISSUE THREAD

**Issue by sigoden** [sigoden/htte#11]
```
- describe: root
  units:
    - describe: g0
      units:
        - describe: g0-0
    - describe: g1
      units:
        - describe: g1-0
```

打印描述现在是这样的

```
root
  g0
    1) g0-0
root
  g1
    2) g1-0
```

其实应该是这样的

```
root
  g0
    1) g0-0
  g1
    2) g1-0
```

测试 `g1-0` 不应该重复打印 `root`
