### ISSUE TITLE
Improve !@object

### ISSUE THREAD

**Issue by sigoden** [sigoden/htte#5]
use suffix '?' to mark value is optional.

```
req:
  body:
    k1: !@exist
    k2?: !@exist
```

`k2` with `?` means k2 is optional.
