### ISSUE TITLE
引入 Mock

### ISSUE THREAD

**Issue by sigoden** [sigoden/htte#9]
新建一款插件其使用 mockjs 生成假数据
```
- describe: mock data
  req:
    body:
      email: !$mock '@EMAIL'
      url: !$mock "@URL('http', 'example.com')"
      arr: !$moco
         'list|1-10': 
           -  'id|+1': 1
```
